name: build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:

jobs:

  build:
    
    permissions:
      contents: write
      pull-requests: write
    
    runs-on: windows-latest

    env:
      Solution_Path: Flow.Launcher.Plugin.ClipboardPlus.sln
      Project_Path: build\Build.csproj

    steps:

      # Checkout codes
      - name: Checkout
        uses: actions/checkout@v4

      # Install the .NET Core workload
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            7.0.x
            8.0.x

      # Restore dependencies for entire solution
      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Path }}

      # Build the entire solution
      - name: Build
        run: dotnet build ${{ env.Solution_Path }} --configuration Release

      # Execute all unit tests in the solution
      - name: Execute unit tests
        run: dotnet test ${{ env.Solution_Path }} --configuration Release --no-build

      # Run the build task
      - name: Run build task
        run: dotnet run --project ${{ env.Project_Path }}

      # Get package version
      - name: Get Package Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: "src/Flow.Launcher.Plugin.ClipboardPlus/plugin.json"
          prop_path: "Version"

      # Upload the Build package
      - name: Upload Build package
        uses: actions/upload-artifact@v4
        with:
          name: "Clipboard+-${{ steps.version.outputs.prop }}.zip"
          path: |
            output/Clipboard+*.zip
            src/Flow.Launcher.Plugin.ClipboardPlus/plugin.json
          compression-level: 0
