name: Publish Release

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - .github/workflows/*
  workflow_dispatch:

jobs:
  publish:
    if: ${{ startsWith(github.event.head_commit.message, 'bump version to') }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'
          cache: false
      
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'src/Flow.Launcher.Plugin.ClipboardPlus/plugin.json'
          prop_path: 'Version'
      
      - run: echo ${{steps.version.outputs.prop}}
      
      - name: Build
        run: dotnet run --project build/Build.csproj
      
      - name: Publish
        uses: softprops/action-gh-release@v2
        with:
          files: ".dist/Clipboard+*"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}